version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopping-cart-api
    container_name: shopping-cart-api
    restart: unless-stopped
    env_file: .env
    environment:
      - API_PORT=$API_PORT
      - MONGODB_HOSTNAME=db
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    networks:
      - api-network
    command: ./docker/wait-for.sh db:27017 -- npm start
  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER_ROOT
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_USERNAME=$MONGODB_USER
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - "27017:27017"
    volumes:
      - ./home/mongodb:/home/mongodb
      - ./docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./database:/data/db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge